FROM hypriot/rpi-alpine

# Install dependencies
RUN apk add -U \
    python3 \
    python3-dev \
    py-pip \
    py-virtualenv
RUN python3 -m ensurepip

COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt
